### ISSUE TITLE
Please add SPDX lines in license headers.

### ISSUE THREAD

**Issue by SanthiSridharan** [capitalone/cqrs-manager-for-distributed-reactive-services#12]
Include the following lines in the license headers within the scripts. This is to ensure that the automated license scanning tools can identify the license.

SPDX-Copyright: Copyright (c) Capital One Services, LLC
SPDX-License-Identifier: Apache-2.0

**Comment by bobby** [comment]
@SanthiSridharan I believe I've addressed this issue via PR #13 .  Please review, and then I'll merge.
