### ISSUE TITLE
Missing docker-compose-example.yml

### ISSUE THREAD

**Issue by danielcompton** [capitalone/cqrs-manager-for-distributed-reactive-services#16]
The README talks about a docker-compose-example.yml file, but I couldn't see it in the repository? If this exists, is it possible to be added to the repo? Thanks, and sorry for all the questions.

**Comment by inadarei** [comment]
@danielcompton I think https://github.com/capitalone/cqrs-manager-for-distributed-reactive-services/pull/17 should contain a proper version of the missing compose file 

I am still getting an error message https://github.com/capitalone/cqrs-manager-for-distributed-reactive-services/issues/18 though :(

@bobby?

**Comment by bobby** [comment]
@danielcompton Good catch, somehow that file went missing when we pushed to public GitHub.  I'll poke around and try to recover it.
