### ISSUE TITLE
How to simulate sync response using kafka ?

### ISSUE THREAD

**Issue by kiranpatel11** [capitalone/cqrs-manager-for-distributed-reactive-services#19]
Note: This is more of a question/clarification rather than an issue.
Hi,

In your architecture, how is the sync response behavior simulated for command processing.

As far as I know, in kafka there is no provision similar to JMSCorrelationId in JMS to correlate response for a given request message.

Any details on this would be helpful.

**Comment by danielcompton** [comment]
Hi @kiranpatel11 

Every command and event has an id. Commands can have children, and events can have parents. These are how commands and events are linked. You can see the specs for this in `com.capitalone.commander`.

Commander provides the sync response by listening on the core.async channel `events-pub` for events that have the command id as their `:parent`. This is provided as a layer on top of Kafka. As you point out, Kafka has no native ability to correlate messages. The code doing this is [here](https://github.com/capitalone/cqrs-manager-for-distributed-reactive-services/blob/b61f08802a8ad484d216e374f4492c7f1b855c65/src/com/capitalone/commander/api.clj#L269-L278) and [here](https://github.com/capitalone/cqrs-manager-for-distributed-reactive-services/blob/b61f08802a8ad484d216e374f4492c7f1b855c65/src/com/capitalone/commander/api.clj#L313-L314).

I'm pretty new to commander so my comment not be 100% accurate, but it should point you in the right direction.

**Comment by bobby** [comment]
Hi @kiranpatel11,

Yes, @danielcompton is correct.  Currently, the sync listener waits for an event whose `parent` is equal to the original command's `id` before returning the HTTP 201 response.  I have some ideas of how to improve this, but that's how it works for now.

Cheers,
Bobby
