### ISSUE TITLE
Example Docker Issue

### ISSUE THREAD

**Issue by maarek** [capitalone/cqrs-manager-for-distributed-reactive-services#24]
I am trying to get the example docker project to run from the makefile. What I am running into is that /usr/src/app/bin/run does not exist. Actually, nothing exists in any of the directories as the Dockerfile only copies up project.clj. Am I missing a step or should sources have been copied up or a locally made jar?

**Comment by SanthiSridharan** [comment]
@bobby - 
Hey Bobby - Would you have bandwidth to answer Jeremy's question ? Just wondering as I dont see any other active contributors supporting this project.

**Comment by maarek** [comment]
Just a quick update. I've confused everything by not noticing the "COPY . /usr/src/app" in the Dockerfile. But this doesn't actually be copying any files in the subdirectories of src, resources, generated, and bin which are excluded in the dockerignore. I'm digging into this and will update if I find anything.

**Comment by maarek** [comment]
After some trial and error, I found out that the following update to the .dockerignore file fixed the issue. Not sure if this was something on osx or docker for mac or what. Anyways, hope this helps anyone who might run into this problem.

```
**

!project.clj
!src/
!src/**
!resources/
!resources/**
!generated/
!generated/**
!bin/
!bin/**
```

**Comment by SanthiSridharan** [comment]
Hey @maarek - DO you want to send a pull request for this - I can see if someone can review and give the go.

**Comment by bobby** [comment]
@maarek Thanks for doing this detective work!  I'll make this change.

**Comment by SanthiSridharan** [comment]
Thanks @bobby
